version: 0.1
component: build
timeoutInSeconds: 20000
runAs: root
shell: bash
steps:
  - type: Command
    name: "Build Hello World"
    timeoutInSeconds: 10000
    command: |
      cd src/com/sample/
      javac HelloWorld.java
    onFailure:
      - type: Command
        command: |
          echo "Building Hello World failed"
        timeoutInSeconds: 1000
        runAs: root
  - type: Command
    timeoutInSeconds: 10000
    name: "Predefined system variables"
    command: |
      echo $OCI_STAGE_ID > output.txt
    onFailure:
      - type: Command
        command: |
          echo "variable printing failed"
        timeoutInSeconds: 1000
        runAs: root
outputArtifacts:
  - name: output
    type: BINARY_IMAGE
    location: output.txt
